#!/usr/bin/env bash

set -e

build_roc() {
    ./roc build --lib \
        --output lib/libmain.so \
        --emit-llvm-ir --prebuilt-platform
}

build_zig() {
    zig build-lib -dynamic -lc \
        -femit-bin="lib/libhost.so" \
        platform/host.zig \
        lib/libmain.so
}

build_all() {
    build_roc
    build_zig
}

case "$1" in
    roc)
        build_roc
        ;;
    zig)
        build_zig
        ;;
    *)
        build_all
        ;;
esac